all:

install:
	mkdir -p $(DESTDIR)/bin
	cp -a start-demo.sh $(DESTDIR)/bin/start-demo
	cp -a nucdemo $(DESTDIR)/bin
	cp -ra lib $(DESTDIR)/
	chmod a+x $(DESTDIR)/bin/start-demo
	chmod a+x $(DESTDIR)/bin/nucdemo
