name: iotivity-demogateway
version: 1.1.0
vendor: Gerald Yang <gerald.yang@canonical.com>
architectures: [amd64]
summary: An Iotivity demo gateway
description: An Iotivity demo gateway, discovers all known resources on local LAN, collects all sensor data and provides some rules.
icon: ./iotivity.png

#binaries:
#    start-demo:
#        exec: start-demo
#        caps:
#            - network-client
#            - network-service

services:
    start-demo:
        start: start-demo
        description: An Iotivity demo gateway
        caps:
            - network-client
            - network-service

parts:
    server:
        plugin: make
        source: .

